### ISSUE TITLE
Error install Dino Saur

### ISSUE THREAD

**Issue by kKen94** [tubbo/saur#4]
I try to install Deno Saur with command

`deno install --unstable --allow-net --allow-env --allow-read=. --allow-write --allow-run --name saur https://deno.land/x/saur/cli.js`

and I get this error: 

```
error: TS2305 [ERROR]: Module '"https://deno.land/std/io/util"' has no exported member 'stringsReader'.
import { stringsReader } from "https://deno.land/std/io/util.ts";
         ~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/tubbo/dejs/fuck-you-github/mod.ts:3:10
```

**Comment by rileyseaburg** [comment]
I don't believe this project is ready for production. 

I'm getting an import error as well from another module. 

> `error: Uncaught SyntaxError: The requested module 'https://deno.land/x/dirname/mod.ts' does not provide an export named '__'
import { __ } from "https://deno.land/x/dirname/mod.ts";
         ~~
    at <anonymous> (https://deno.land/x/saur@v0.0.1/cli/generate/template.js:3:10)`
